apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dockercommsweb
  namespace: svc-development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: webcontainer
        image: glavregsistry.azurecr.io/dockercommsweb
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dockercommsapi
  namespace: svc-development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - name: apicontainer
        image: glavregsistry.azurecr.io/dockercommsapi
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dockercomms-front-end
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
  - port: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: apicontainer
spec:
  type: NodePort
  selector:
    app: api-app
  ports:
  - port: 80
    protocol: TCP