version: '3.4'

services:
  webcontainer:
    image: ${DOCKER_REGISTRY}dockercommsweb
    build:
      context: ./DockerComms-Web
      dockerfile: Dockerfile

  apicontainer:
    image: ${DOCKER_REGISTRY}dockercommsapi
    build:
      context: ./DockerComms-api
      dockerfile: Dockerfile
